-- AlterTable
ALTER TABLE "Confirmation" ADD COLUMN     "confirmedat" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Registration" ADD COLUMN     "registeredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Ticket" ADD COLUMN     "madeat" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
